name: Rust

on:
  pull_request:
  push:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_ARGS: "--all-targets --all-features"
  CLIPPY_OPTS: "-D warnings -W clippy::pedantic -W clippy::nursery -D clippy::unchecked_duration_subtraction"

jobs:
  fmt-clippy:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        pacman -Sy --noconfirm base-devel gtk4 gtk4-layer-shell rustup
        rustup default stable
    - name: Format
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy $CARGO_ARGS -- $CLIPPY_OPTS
    - name: Clippy for tests
      run: cargo clippy --tests $CARGO_ARGS -- $CLIPPY_OPTS
    - name: Clippy for benches
      run: cargo clippy --benches $CARGO_ARGS -- $CLIPPY_OPTS
  tests:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm base-devel gtk4 gtk4-layer-shell rustup
          rustup default stable
      - name: Test
        run: cargo test $CARGO_ARGS
